// Workouts
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const INITIALIZE_WORKOUTS = 'INITIALIZE_WORKOUTS';

// Cycles
export const INITIALIZE_CYCLES = 'INITIALIZE_CYCLES';
export const DECREMENT_SELECTED_CYCLE_INDEX = 'DECREMENT_SELECTED_CYCLE_INDEX';
export const INCREMENT_SELECTED_CYCLE_INDEX = 'INCREMENT_SELECTED_CYCLE_INDEX';
export const ADD_CYCLE = 'ADD_CYCLE';
export const DELETE_CYCLE = 'DELETE_CYCLE';

// Exercises
export const INITIALIZE_EXERCISES = 'INITIALIZE_EXERCISES';

// Misc
export const COLORS = ['#CAB0FF', '#9D8DFF', '#6D8DFF'];