version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm ci
      - npm run lint
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
